/**
 * Android export — `res/values/colors.xml` (ARGB hex, light + a night
 * qualifier) and a Kotlin object for Compose — from the same `buildTokens`
 * output the web and iOS exports read. One source, three platforms.
 */
import { buildTokens } from '../tokens/buildTokens'
import { tokenHex } from './genSwift'
import type { Config } from '../tokens/types'

const COLORS: Array<[string, string]> = [
  ['primary', '--k-primary'], ['primary_hover', '--k-primary-hover'], ['on_primary', '--k-primary-fg'], ['primary_container', '--k-primary-soft'],
  ['secondary', '--k-secondary'], ['tertiary', '--k-accent'],
  ['background', '--k-bg'], ['surface', '--k-surface'], ['surface_variant', '--k-surface-sunken'],
  ['on_surface', '--k-fg'], ['on_surface_muted', '--k-fg-muted'], ['outline', '--k-input-border'], ['outline_variant', '--k-border'],
  ['success', '--k-success'], ['warning', '--k-warning'], ['error', '--k-danger'], ['info', '--k-info'],
]
const argb = (hex: string) => '#FF' + hex.slice(1).toUpperCase()
const kotlinName = (n: string) => n.split('_').map((p, i) => (i ? p[0]!.toUpperCase() + p.slice(1) : p)).join('')

export function genAndroidColorsXml(cfg: Config, mode: 'light' | 'dark' = 'light'): string {
  const v = buildTokens({ ...cfg, mode }).vars
  const rows = COLORS.map(([name, key]) => { const h = tokenHex(v[key]); return h ? `    <color name="${name}">${argb(h)}</color>` : `    <!-- ${name}: ${v[key]} (not a flat colour) -->` })
  return `<?xml version="1.0" encoding="utf-8"?>\n<!-- generated by UISandbox — values${mode === 'dark' ? '-night' : ''}/colors.xml -->\n<resources>\n${rows.join('\n')}\n</resources>\n`
}

export function genAndroidKotlin(cfg: Config): string {
  const light = buildTokens({ ...cfg, mode: 'light' }).vars
  const dark = buildTokens({ ...cfg, mode: 'dark' }).vars
  const px = (x: string | number | undefined) => { const m = String(x ?? '').match(/^(-?\d*\.?\d+)(px|rem)$/); return m ? Math.round((m[2] === 'rem' ? +m[1]! * 16 : +m[1]!) * 10) / 10 : null }
  const rows = (v: Record<string, string | number>) => COLORS.map(([name, key]) => { const h = tokenHex(v[key]); return h ? `        val ${kotlinName(name)} = Color(0xFF${h.slice(1).toUpperCase()})` : `        // ${name}: ${v[key]}` })
  return `// DesignTokens.kt — generated by UISandbox from the values in the sandbox.
package design

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

object DesignTokens {
    object Light {
${rows(light).join('\n')}
    }
    object Dark {
${rows(dark).join('\n')}
    }
    object Radius {
        val small = ${px(light['--k-radius-sm']) ?? 6}.dp
        val medium = ${px(light['--k-radius-md']) ?? 10}.dp
        val large = ${px(light['--k-radius-lg']) ?? 12}.dp
    }
    object Space {
        val unit = ${px(light['--k-space']) ?? 16}.dp
        val pad = ${px(light['--k-pad']) ?? 24}.dp
        val gap = ${px(light['--k-gap']) ?? 8}.dp
    }
    object Type {
        val display = ${px(light['--k-type-display']) ?? 48}.sp
        val h1 = ${px(light['--k-type-h1']) ?? 30}.sp
        val h2 = ${px(light['--k-type-h2']) ?? 22}.sp
        val body = ${px(light['--k-type-body']) ?? 14}.sp
        val small = ${px(light['--k-type-small']) ?? 12}.sp
    }
}
`
}
