/**
 * iOS export — the tokens as Swift constants (SwiftUI `Color`/`CGFloat`/`Font`)
 * and an asset-catalog colour set per brand token. From the same `buildTokens`
 * output the web exports read: one source, two platforms.
 *
 * Honest scope (PROMPT.md, hard nut 1): there is no 1:1 render of an iOS app
 * in a browser. What we CAN promise is that the values a designer settled on
 * in the sandbox arrive in Xcode exactly — light and dark.
 */
import { buildTokens } from '../tokens/buildTokens'
import { oklchStrToHex } from '../tokens/color'
import { customFontFamily } from '../tokens/fonts'
import type { Config } from '../tokens/types'

const COLOR_KEYS: Array<[string, string]> = [
  ['primary', '--k-primary'], ['primaryHover', '--k-primary-hover'], ['primaryForeground', '--k-primary-fg'], ['primarySoft', '--k-primary-soft'],
  ['secondary', '--k-secondary'], ['accent', '--k-accent'],
  ['background', '--k-bg'], ['surface', '--k-surface'], ['surfaceSunken', '--k-surface-sunken'], ['surfaceRaised', '--k-surface-raised'],
  ['foreground', '--k-fg'], ['foregroundMuted', '--k-fg-muted'], ['foregroundFaint', '--k-fg-faint'],
  ['border', '--k-border'], ['inputBorder', '--k-input-border'], ['ring', '--k-ring'],
  ['success', '--k-success'], ['warning', '--k-warning'], ['danger', '--k-danger'], ['info', '--k-info'],
]
const LENGTH_KEYS: Array<[string, string]> = [
  ['radiusSmall', '--k-radius-sm'], ['radiusMedium', '--k-radius-md'], ['radiusLarge', '--k-radius-lg'],
  ['space', '--k-space'], ['pad', '--k-pad'], ['gap', '--k-gap'],
  ['spacing2', '--k-s-2'], ['spacing4', '--k-s-4'], ['spacing8', '--k-s-8'], ['spacing12', '--k-s-12'], ['spacing16', '--k-s-16'], ['spacing24', '--k-s-24'], ['spacing32', '--k-s-32'],
  ['controlHeight', '--k-in-h-default'], ['buttonHeight', '--k-btn-h-default'],
]
const TYPE_KEYS: Array<[string, string]> = [
  ['display', '--k-type-display'], ['h1', '--k-type-h1'], ['h2', '--k-type-h2'], ['h3', '--k-type-h3'],
  ['body', '--k-type-body'], ['small', '--k-type-small'], ['caption', '--k-type-caption'],
]

/** Any token colour → #rrggbb (or null for something we cannot flatten, like a color-mix). */
export function tokenHex(v: string | number | undefined): string | null {
  if (v === undefined) return null
  const s = String(v).trim()
  if (/^#[0-9a-f]{6}$/i.test(s)) return s.toLowerCase()
  if (/^oklch\(/i.test(s)) { try { return oklchStrToHex(s) } catch { return null } }
  return null
}
const pts = (v: string | number | undefined): number | null => {
  const m = String(v ?? '').trim().match(/^(-?\d*\.?\d+)(px|rem)$/)
  if (!m) return null
  const n = parseFloat(m[1]!)
  return Math.round((m[2] === 'rem' ? n * 16 : n) * 100) / 100
}
const swiftHex = (hex: string) => {
  const r = parseInt(hex.slice(1, 3), 16) / 255, g = parseInt(hex.slice(3, 5), 16) / 255, b = parseInt(hex.slice(5, 7), 16) / 255
  return `Color(red: ${r.toFixed(4)}, green: ${g.toFixed(4)}, blue: ${b.toFixed(4)})`
}

export function genSwift(cfg: Config): string {
  const light = buildTokens({ ...cfg, mode: 'light' }).vars
  const dark = buildTokens({ ...cfg, mode: 'dark' }).vars
  const colors = COLOR_KEYS.map(([name, key]) => {
    const l = tokenHex(light[key]), d = tokenHex(dark[key])
    if (!l) return `    // ${name}: ${light[key]} (not a flat colour — see tokens.css)`
    return `    static let ${name} = Color(light: ${swiftHex(l)}, dark: ${swiftHex(d ?? l)}) // ${l} / ${d ?? l}`
  })
  const lengths = LENGTH_KEYS.map(([name, key]) => {
    const p = pts(light[key])
    return p === null ? `    // ${name}: ${light[key]}` : `    static let ${name}: CGFloat = ${p}`
  })
  const type = TYPE_KEYS.map(([name, key]) => {
    const p = pts(light[key])
    return p === null ? `    // ${name}: ${light[key]}` : `    static let ${name}: CGFloat = ${p}`
  })
  const family = (n: string) => (n === 'System' ? null : customFontFamily(n))
  const disp = family(cfg.fontDisplay), body = family(cfg.fontBody)
  return `// DesignTokens.swift — generated by UISandbox from the values in the sandbox.
// Drop into your Xcode project. Custom fonts must be added to the bundle + Info.plist.
import SwiftUI

extension Color {
    /// A colour that follows the system appearance.
    init(light: Color, dark: Color) {
        self.init(uiColor: UIColor { trait in
            trait.userInterfaceStyle == .dark ? UIColor(dark) : UIColor(light)
        })
    }
}

enum DesignTokens {
    enum Colors {
${colors.join('\n')}
    }

    enum Metrics {
${lengths.join('\n')}
    }

    enum TypeSize {
${type.join('\n')}
    }

    enum Fonts {
        static let displayFamily: String? = ${disp ? `"${disp}"` : 'nil // system'}
        static let bodyFamily: String? = ${body ? `"${body}"` : 'nil // system'}
        static func display(_ size: CGFloat, weight: Font.Weight = .semibold) -> Font {
            displayFamily.map { Font.custom($0, size: size).weight(weight) } ?? .system(size: size, weight: weight, design: .default)
        }
        static func body(_ size: CGFloat = TypeSize.body, weight: Font.Weight = .regular) -> Font {
            bodyFamily.map { Font.custom($0, size: size).weight(weight) } ?? .system(size: size, weight: weight, design: .default)
        }
    }
}
`
}

/** An asset-catalog `Contents.json` per colour set (light + dark appearances). */
export function genAssetCatalog(cfg: Config): Array<{ path: string; content: string }> {
  const light = buildTokens({ ...cfg, mode: 'light' }).vars
  const dark = buildTokens({ ...cfg, mode: 'dark' }).vars
  const out: Array<{ path: string; content: string }> = [
    { path: 'DesignTokens.xcassets/Contents.json', content: JSON.stringify({ info: { author: 'uisandbox', version: 1 } }, null, 2) + '\n' },
  ]
  const comp = (hex: string) => ({
    'color-space': 'srgb',
    components: { red: `0x${hex.slice(1, 3).toUpperCase()}`, green: `0x${hex.slice(3, 5).toUpperCase()}`, blue: `0x${hex.slice(5, 7).toUpperCase()}`, alpha: '1.000' },
  })
  for (const [name, key] of COLOR_KEYS) {
    const l = tokenHex(light[key]), d = tokenHex(dark[key])
    if (!l) continue
    const set = {
      info: { author: 'uisandbox', version: 1 },
      colors: [
        { idiom: 'universal', color: comp(l) },
        { idiom: 'universal', appearances: [{ appearance: 'luminosity', value: 'dark' }], color: comp(d ?? l) },
      ],
    }
    const setName = name.charAt(0).toUpperCase() + name.slice(1)
    out.push({ path: `DesignTokens.xcassets/${setName}.colorset/Contents.json`, content: JSON.stringify(set, null, 2) + '\n' })
  }
  return out
}
